#
###################################
# Site wide configuration
####################################
#
title: William Bradford Larcombe
email: william@williambl.com
description: > # this means to ignore newlines until "baseurl:"
  Creator of games, mods, and other programs.
  Things I've made include DeltaMC, the Haunt, and the EssentialFeatures minecraft mod.
  I often participate in Ludum Dares.
formatted_description: >
  Creator of games, mods, and other programs.
  Things I've made include [DeltaMC](https://github.com/deltamc-project), [the Haunt](https://github.com/williambl/Haunt), and the [EssentialFeatures](https://github.com/williambl/EssentialFeatures) minecraft mod.
  I often participate in Ludum Dares. 
url: http://localhost:4000
#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter:  pygments
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: William Bradford Larcombe
  avatar: WBL/WBL0-378px.jpeg
  job: "Developer"
  bio: "Creator of games, mods, and other programs.
  Things I've made include DeltaMC, the Haunt, and the EssentialFeatures minecraft mod.
  I often participate in Ludum Dares."
  email: william@williambl.com
  disqus-shortname:
  twitter: williambl_
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: williambl
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
