#
###################################
# Site wide configuration
####################################
#
description: "I make things. Sometimes they're not bad. <em>Sometimes.</em>"
long_description: >
  Hi!
  I sometimes make things, usually with code. You can see a small selection down below. I also often participate in Ludum Dares, and sometimes other game jams (if I remember when they happen!)
url: https://williambl.com
favicon: 
#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter:  rouge
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

# plugins:
#   - jekyll-postcss
#   - jekyll-purgecss

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - netlify.toml
  - bin
  - .gitignore
#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Will BL
  avatar: "WBL/gh-avatar-460.jpeg"
  job: "Software Developer"
  bio: "I make things. Sometimes they're not bad. <em>Sometimes.</em>"
  email: william@williambl.com
  disqus-shortname:
  twitter:
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: williambl
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
