#
###################################
# Site wide configuration
####################################
#
title: William Bradford Larcombe
email: william@williambl.com
description: > # this means to ignore newlines until "baseurl:"
  Creator of games, mods, unity assets, and other things. Also often Ludum Dare participant.
long_description: >
  Creator of games, mods, unity assets, and other things.
  Things I've made include [unity-destruction](https://github.com/williambl/unity-destruction), [DeltaMC](https://github.com/deltamc-project), and the [EssentialFeatures](https://github.com/williambl/EssentialFeatures) minecraft mod.
  I often participate in Ludum Dares.
url: https://williambl.com
favicon: WBL/WBL0-128px-square.png
collections:
  code-games:
    title: Games
    type: code
    link: /my-stuff/code/games
    output: true
  code-interlok:
    title: Interlok
    type: code
    link: /my-stuff/code/interlok
    output: true
  code-minecraft:
    title: Minecraft Mods et cetera
    type: code
    link: /my-stuff/code/minecraft
    output: true
  code-misc:
    title: Miscellaneous
    type: code
    link: /my-stuff/code/misc
    output: true
  code-unity-assets:
    title: Unity Assets
    type: code
    link: /my-stuff/code/unity-assets
    output: true
  video-informative:
    title: Informative
    type: video
    link: /my-stuff/video/informative
    output: true
  video-memes:
    title: Memes
    type: video
    link: /my-stuff/video/memes
    output: true
  video-misc:
    title: Miscellaneous
    type: video
    link: /my-stuff/video/misc
    output: true

#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter:  rouge
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: William Bradford Larcombe
  avatar: WBL/WBL0-378px-square.jpeg
  job: "Developer"
  bio: Creator of games, mods, unity assets, and other things. Also often Ludum Dare participant.
  email: william@williambl.com
  disqus-shortname:
  twitter: williambl_
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: williambl
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
