#
###################################
# Site wide configuration
####################################
#
title: Will BL
description: "I make things. Maybe you'll enjoy some of them?"
long_description: >
  Hi!
  I make things, usually with code. You can see a small selection of things I've made down below. I do most of my programming for game modding, and I also often participate in game jams such as Ludum Dare (if I remember when they happen!). My favourite language is Kotlin, but I am also proficient in Java and a few others.
url: https://willbl.dev/
favicon: WBL/gh-avatar-460.png
#
###################################
# Jekyll configuration
####################################
#
markdown:    kramdown
highlighter:  rouge
excerpt_separator: <!--more-->

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

plugins:
  - jekyll-postcss
  - jekyll-purgecss
css_dir: "css"


exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - yarn.lock
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - netlify.toml
  - bin
  - .gitignore
#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Will BL
  avatar: "WBL/gh-avatar-460.png"
  job: "Software Developer"
  bio: "I make things. Maybe you'll enjoy some of them?"
  email: william@williambl.com
  disqus-shortname:
  twitter:
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: williambl
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
